services:
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: compliance-db
    environment:
      POSTGRES_USER: compliance
      POSTGRES_PASSWORD: compliance_dev
      POSTGRES_DB: compliance_mapping
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U compliance -d compliance_mapping"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compliance-app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://compliance:compliance_dev@db:5432/compliance_mapping
      DATABASE_URL_SYNC: postgresql+psycopg2://compliance:compliance_dev@db:5432/compliance_mapping
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
